// frontends/web-react/src/components/RevenueChart.tsx
import { formatClock, formatCompact, formatMad, type TimePoint } from "@rad/core";
import { memo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

import { COLORS } from "../config";
import { useRenderTrace } from "../renderTrace";

type Granularity = "minute" | "hour";

interface Props {
  minute: TimePoint[];
  hour: TimePoint[];
}

const LABELS: Record<Granularity, string> = { minute: "Per minute · 1 h", hour: "Per hour · 24 h" };

export const RevenueChart = memo(function RevenueChart({ minute, hour }: Props) {
  useRenderTrace("revenue");
  const [granularity, setGranularity] = useState<Granularity>("minute");
  const data = granularity === "minute" ? minute : hour;

  return (
    <>
      <div className="card-header">
        <h2>Revenue</h2>
        <div className="segmented" role="tablist" aria-label="Granularity">
          {(Object.keys(LABELS) as Granularity[]).map((g) => (
            <button
              key={g}
              type="button"
              role="tab"
              aria-selected={g === granularity}
              className={g === granularity ? "active" : undefined}
              onClick={() => setGranularity(g)}
            >
              {LABELS[g]}
            </button>
          ))}
        </div>
      </div>
      <div className="chart">
        <ResponsiveContainer width="100%" height="100%">
          <AreaChart data={data} margin={{ top: 8, right: 12, bottom: 0, left: 0 }}>
            <defs>
              <linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%" stopColor={COLORS.accent} stopOpacity={0.4} />
                <stop offset="100%" stopColor={COLORS.accent} stopOpacity={0} />
              </linearGradient>
            </defs>
            <CartesianGrid stroke={COLORS.grid} vertical={false} />
            <XAxis
              dataKey="bucket"
              tickFormatter={(value: string) => formatClock(value)}
              minTickGap={40}
              stroke={COLORS.muted}
              tickLine={false}
            />
            <YAxis
              tickFormatter={(value: number) => formatCompact(value)}
              width={52}
              stroke={COLORS.muted}
              tickLine={false}
              axisLine={false}
            />
            <Tooltip
              contentStyle={{ background: "#141925", border: `1px solid ${COLORS.grid}`, borderRadius: 8 }}
              labelFormatter={(label) => formatClock(String(label))}
              formatter={(value) => [formatMad(Number(value)), "Revenue"]}
            />
            {/* No animation: each live update would otherwise replay the drawing animation
                on the whole line, which reads as flicker. */}
            <Area
              type="monotone"
              dataKey="revenue_mad"
              stroke={COLORS.accent}
              strokeWidth={2}
              fill="url(#revenueFill)"
              dot={false}
              isAnimationActive={false}
            />
          </AreaChart>
        </ResponsiveContainer>
      </div>
    </>
  );
});

// frontends/web-angular/src/app/components/revenue-chart.component.ts
import { ChangeDetectionStrategy, Component, computed, input, signal } from '@angular/core';
import { formatClock, formatCompact, formatMad, type TimePoint } from '@rad/core';
import type { EChartsCoreOption } from 'echarts/core';
import { NgxEchartsDirective } from 'ngx-echarts';

import { COLORS } from '../config';

type Granularity = 'minute' | 'hour';

@Component({
  selector: 'app-revenue-chart',
  imports: [NgxEchartsDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="card-header">
      <h2>Revenue</h2>
      <div class="segmented" role="tablist" aria-label="Granularity">
        @for (option of granularities; track option.value) {
          <button
            type="button"
            role="tab"
            [attr.aria-selected]="option.value === granularity()"
            [class.active]="option.value === granularity()"
            (click)="granularity.set(option.value)"
          >
            {{ option.label }}
          </button>
        }
      </div>
    </div>
    <!-- [options] is applied once; [merge] only carries new data. ECharts keeps the same chart
         instance and animates the change, instead of redrawing from scratch (no flicker). -->
    <div class="chart" echarts [options]="baseOptions" [merge]="data()"></div>
  `,
})
export class RevenueChartComponent {
  readonly minute = input.required<TimePoint[]>();
  readonly hour = input.required<TimePoint[]>();

  protected readonly granularity = signal<Granularity>('minute');
  protected readonly granularities: { value: Granularity; label: string }[] = [
    { value: 'minute', label: 'Per minute · 1 h' },
    { value: 'hour', label: 'Per hour · 24 h' },
  ];

  protected readonly baseOptions: EChartsCoreOption = {
    animationDurationUpdate: 300,
    grid: { left: 56, right: 16, top: 16, bottom: 28 },
    tooltip: {
      trigger: 'axis',
      valueFormatter: (value: unknown) => formatMad(Number(value)),
    },
    xAxis: {
      type: 'category',
      boundaryGap: false,
      axisLabel: { color: COLORS.muted },
      axisLine: { lineStyle: { color: COLORS.grid } },
    },
    yAxis: {
      type: 'value',
      axisLabel: { color: COLORS.muted, formatter: (value: number) => formatCompact(value) },
      splitLine: { lineStyle: { color: COLORS.grid } },
    },
    series: [
      {
        name: 'Revenue',
        type: 'line',
        smooth: true,
        showSymbol: false,
        lineStyle: { color: COLORS.accent, width: 2 },
        itemStyle: { color: COLORS.accent },
        areaStyle: {
          color: {
            type: 'linear',
            x: 0,
            y: 0,
            x2: 0,
            y2: 1,
            colorStops: [
              { offset: 0, color: 'rgba(79, 140, 255, 0.4)' },
              { offset: 1, color: 'rgba(79, 140, 255, 0)' },
            ],
          },
        },
      },
    ],
  };

  protected readonly data = computed<EChartsCoreOption>(() => {
    const points = this.granularity() === 'minute' ? this.minute() : this.hour();
    return {
      xAxis: { data: points.map((point) => formatClock(point.bucket)) },
      series: [{ data: points.map((point) => point.revenue_mad) }],
    };
  });
}
