// frontends/web-angular/src/app/components/event-feed.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { EVENT_LABELS, formatMad, type FeedEvent } from '@rad/core';

@Component({
  selector: 'app-event-feed',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="card-header">
      <h2>Live events</h2>
      <span class="muted">newest first</span>
    </div>
    @if (events().length === 0) {
      <p class="empty">Waiting for events…</p>
    } @else {
      <ul class="feed">
        <!-- track by event id: only new rows are created (and play the highlight animation). -->
        @for (event of events(); track event.event_id) {
          <li class="feed-row">
            <span class="feed-time">{{ clock(event.occurred_at) }}</span>
            <span [class]="'chip chip-' + event.event_type">{{ labels[event.event_type] }}</span>
            <span class="feed-amount">{{ mad(event.amount_mad) }}</span>
            <span class="feed-meta">
              {{ event.category }} · {{ event.city }} · {{ event.payment_method.replaceAll('_', ' ') }}
            </span>
          </li>
        }
      </ul>
    }
  `,
})
export class EventFeedComponent {
  readonly events = input.required<FeedEvent[]>();

  protected readonly labels = EVENT_LABELS;
  protected readonly mad = formatMad;

  protected clock(iso: string): string {
    return new Date(iso).toLocaleTimeString([], { hour12: false });
  }
}

// frontends/web-react/src/components/EventFeed.tsx
import { EVENT_LABELS, formatMad, type FeedEvent } from "@rad/core";
import { memo } from "react";

import { useRenderTrace } from "../renderTrace";

function clock(iso: string): string {
  return new Date(iso).toLocaleTimeString([], { hour12: false });
}

export const EventFeed = memo(function EventFeed({ events }: { events: FeedEvent[] }) {
  useRenderTrace("feed");
  return (
    <>
      <div className="card-header">
        <h2>Live events</h2>
        <span className="muted">newest first</span>
      </div>
      {events.length === 0 ? (
        <p className="empty">Waiting for events…</p>
      ) : (
        <ul className="feed">
          {events.map((event) => (
            // Stable keys: only new rows mount (and play the highlight animation).
            <li key={event.event_id} className="feed-row">
              <span className="feed-time">{clock(event.occurred_at)}</span>
              <span className={`chip chip-${event.event_type}`}>{EVENT_LABELS[event.event_type]}</span>
              <span className="feed-amount">{formatMad(event.amount_mad)}</span>
              <span className="feed-meta">
                {event.category} · {event.city} · {event.payment_method.replaceAll("_", " ")}
              </span>
            </li>
          ))}
        </ul>
      )}
    </>
  );
});
